version: '2'

services:
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    hostname: 'kafka'
    ports:
      - 9092:9092
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: '127.0.0.1'
      KAFKA_ADVERTISED_LISTENERS: 'INSIDE://:9094,OUTSIDE://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
      KAFKA_LISTENERS: 'INSIDE://:9094,OUTSIDE://:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INSIDE'
      KAFKA_CREATE_TOPICS: 'example:3:1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: 'zookeeper'
    ports:
      - 2181:2181
